thistuple = ("apple", "banana", "cherry")
print(thistuple)
createtuple=tuple((1,2,3,4,"a","bhjbkd",6))
print(type(createtuple))
print(len(createtuple))
print(createtuple)
print(createtuple[2])
print(createtuple[4:7])
print(createtuple[-5:-2])
print(createtuple[-3:-1])
